# Generated by Django 2.1 on 2018-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20181106_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10),
        ),
    ]
